/**
 * Page/content media under public/media/content/.
 * Manifest generated by scripts/generate-media-manifest.mjs
 */

import { mediaUrl, mediaVideoUrl } from "./resolveAssetUrl";

function content(basename: string): string {
  return mediaUrl("content", basename);
}

function contentVideo(basename: string): string {
  return mediaVideoUrl("content", basename);
}

export const CONTENT_IMAGES = {
  man_on_phone: content("man_on_phone"),
  get_in_touch: content("get-in-touch"),
  contact_form: content("contact-form"),
  contact_bg: content("contact-bg"),
  man_look_ltr: content("man-look-ltr"),
  man_looking_rtl: content("man-looking-rtl"),
  app_bg: content("app-bg"),
  app_phone_screen: content("app-phone-screen"),
  client_dpm: content("client-dpm"),
  client_ifo: content("client-ifo"),
  /** Real Assets diversity card header — any of .svg/.avif/.webp/.jpg/.jpeg/.png */
  ra_diversity: content("ra-diversity"),
  /** Real Assets geographic card header — any of .svg/.avif/.webp/.jpg/.jpeg/.png */
  ra_geo_network: content("ra-geo-network"),
  /** Real Assets project fact cards (ScrollExamples) */
  ra_1: content("ra-1"),
  ra_2: content("ra-2"),
  ra_3: content("ra-3"),
  ra_4: content("ra-4"),
  /** Real Assets projects section background */
  projects_bg: content("projects-bg"),
  private_offers: content("private_offers"),
  who_we_are_intro: content("who-we-are-intro"),
  our_services_arrangement_management: content(
    "our-services-arrangement-managment",
  ),
  service_asset_management: content("service-asset-management"),
  liquidity_fixed_income_intro: content("liquidity-fixed-income-intro"),
  family_office_intro: content("family-office-intro"),
  asset_management_active_card: content("asset-management-active-card"),
  service_investment_banking: content("service-investment-banking"),
  investment_banking_intro: content("investment-banking-intro"),
  section_bg_our_approach: content("section-bg-our-approach"),
  client_solutions_section: content("client-solutions-section"),
  wm_independent_thinking: content("wm-independent-thinking"),
  wm_long_term_partnership: content("wm-long-term-partnership"),
  wm_tailored_strategies: content("wm-tailored-strategies"),
  wm_transparent_reporting: content("wm-transparent-reporting"),
  wm_understanding_goals: content("wm-understanding-goals"),
} as const;

function investmentAdvisory(basename: string): string {
  return mediaUrl("investment-advisory", basename);
}

function investmentAdvisoryVideo(basename: string): string {
  return mediaVideoUrl("investment-advisory", basename);
}

/** Process timeline images for Investment Advisory (`ia-process-1` … `ia-process-5`). */
export const IA_PROCESS_IMAGES = {
  1: investmentAdvisory("ia-process-1"),
  2: investmentAdvisory("ia-process-2"),
  3: investmentAdvisory("ia-process-3"),
  4: investmentAdvisory("ia-process-4"),
  5: investmentAdvisory("ia-process-5"),
} as const;

/**
 * Intro card background (`ia-bg`) — applied inside the rounded advisory card.
 * Drop `ia-bg.mp4` and/or `ia-bg.avif|webp|jpg|png` under
 * `src/assets/investment-advisory` → copy to `public/media/investment-advisory`.
 * Video is preferred when both exist.
 */
export const IA_BG = {
  image: investmentAdvisory("ia-bg"),
  video: investmentAdvisoryVideo("ia-bg"),
} as const;

/** Arrangement “More Detailed Information” section background (`details-pg`). */
export const DETAILS_PG_IMAGE = investmentAdvisory("details-pg");

/** Intro split image (`ia-intro`) — Arrangement Management intro card. */
export const IA_INTRO_IMAGE = investmentAdvisory("ia-intro");

/** Optional short looping videos (preferred over still when both exist). */
export const CONTENT_VIDEOS = {
  app_phone_screen: contentVideo("app-phone-screen"),
  client_dpm: contentVideo("client-dpm"),
  client_ifo: contentVideo("client-ifo"),
} as const;
